AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Python ETL Process for NY Times/JHU COVID-19 Data
  Project is for ACloudGuru September Challenge

Globals:
  Function:
    Timeout: 60

Resources:
  DBBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  DBUpdateTopic:
    Type: AWS::SNS::Topic

  SNSTopicSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref DBUpdateTopic
      Endpoint: jviloria96744@gmail.com
      Protocol: email
      FilterPolicy:
        environment:
          - testing
          - production

  SmokeTestQueue:
    Type: AWS::SQS::Queue

  SmokeTestTopicSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref DBUpdateTopic
      Endpoint: !GetAtt
        - SmokeTestQueue
        - Arn
      Protocol: sqs
      FilterPolicy:
        environment:
          - testing

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          Sid: allow-sns-to-send-message-to-sqs
          Effect: Allow
          Principal:
            Service: sns.amazonaws.com
          Action:
            - sqs:SendMessage
          Resource: !GetAtt SmokeTestQueue.Arn
          Condition:
            ArnEquals:
              aws:SourceArn: !Ref DBUpdateTopic
      Queues:
        - !Ref SmokeTestQueue

  SNSLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sns_lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt DBUpdateTopic.TopicName
      Environment:
        Variables:
          TOPIC_ARN: !Ref DBUpdateTopic
      EventInvokeConfig:
        MaximumRetryAttempts: 0

  PythonEtlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python_etl/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 256
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DBBucket
        - LambdaInvokePolicy:
            FunctionName: !Ref SNSLambdaFunction
      Environment:
        Variables:
          BUCKET_NAME: !Ref DBBucket
          PROD_NYT_URL: "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us.csv"
          PROD_JH_URL: "https://raw.githubusercontent.com/datasets/covid-19/master/data/time-series-19-covid-combined.csv"
          PREV_DATA: "acg-covid-data.csv"
          CHANGE_LOG: "CHANGE_LOG.csv"
          TEST_NYT_URL: "https://gist.githubusercontent.com/jviloria96744/c5b713facc72861a6facdb437667e937/raw/5c8da6b2fec7f18fc22c0067dbf7479a6ae49fcc/test_nyt_data.csv"
          TEST_JH_URL: "https://gist.githubusercontent.com/jviloria96744/c5b713facc72861a6facdb437667e937/raw/5c8da6b2fec7f18fc22c0067dbf7479a6ae49fcc/test_jh_data.csv"
      Events:
        CWSchedule:
          Type: Schedule
          Input: '{"environment": "production"}'
          Properties:
            Schedule: "cron(0 21 * * ? *)"
            Description: Daily scheduling to download COVID-19 data from NY Times and JHU Sources
            Enabled: False
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 60
        MaximumRetryAttempts: 0
        DestinationConfig:
          OnSuccess:
            Type: Lambda
            Destination: !GetAtt SNSLambdaFunction.Arn
          OnFailure:
            Type: Lambda
            Destination: !GetAtt SNSLambdaFunction.Arn

Outputs:
  PythonEtlFunction:
    Description: "Python ETL Function ARN"
    Value: !Ref PythonEtlFunction
  PythonEtlFunctionIamRole:
    Description: "Implicit IAM Role created for Python ETL Function"
    Value: !GetAtt PythonEtlFunctionRole.Arn
  EtlDatabaseBucket:
    Description: "Python ETL S3 Bucket Name"
    Value: !Ref DBBucket
  SmokeTestQueue:
    Description: "SQS Queue URL used for smoke testing in CI/CD Workflow"
    Value: !Ref SmokeTestQueue
