name: Python ETL Challenge CI/CD Back-End
on:
  push:
    paths:
      - "python_etl/**"
      - "sns_lambda/**"
      - "template.yaml"
      - ".github/**"
      - "tests/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Run Unit Tests
        run: |
          pip3 install pytest boto3 moto[s3] moto[sns] pandas
          pytest -v
      - name: Build Project Artifact
        run: sam build --use-container
      - name: Deploy Resources
        run: sam deploy --stack-name python-etl-challenge --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }} --s3-bucket ${{ secrets.AWS_S3_SAM_BUCKET }} --no-fail-on-empty-changeset
      # - name: Smoke Test
      #   run: python3 tests/smoke_test.py
